# Generated by Django 5.0.4 on 2024-05-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(choices=[('SMTP_SERVER', 'SMTP server')], db_column='tx_key', max_length=100, unique=True, verbose_name='Key'),
        ),
    ]
